# Options for analysis running
run:
  # Timeout for analysis, e.g. 30s, 5m
  timeout: 5m

  # Include test files or not
  tests: true

  # Allow multiple parallel golangci-lint instances running
  allow-parallel-runners: true

# Output configuration options
output:
  # Format settings
  sort-results: true
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: false
  format: colored-line-number

# Linters settings
linters-settings:
  govet:
    # Report about shadowed variables
    enable-all: false
    check-shadowing: false
    fieldalignment: true
  gofmt:
    # Simplify code: gofmt with `-s` option
    simplify: true
  gocyclo:
    # Minimal code complexity to report
    min-complexity: 15
  dupl:
    # Tokens count to trigger issue
    threshold: 100
  goconst:
    # Minimal length of string constant
    min-len: 3
    # Minimal occurrences count to trigger
    min-occurrences: 3
  misspell:
    # Correct spellings using locale preferences
    locale: US
  lll:
    # Max line length, lines longer will be reported
    line-length: 120
    # Tab width in spaces
    tab-width: 4
  unused:
    # Treat code as a program (not a library)
    check-exported: false
  unparam:
    # Call this many times before being reported
    algo: cha
    check-exported: false

# Linters
linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gocyclo
    - gofmt
    - goimports
    - misspell
    - unconvert
    - lll

# Issues configuration
issues:
  # Maximum count of issues with the same text
  max-same-issues: 3

  # Maximum issues count per one linter
  max-issues-per-linter: 50

  # Exclude some dirs/files from analysis
  exclude-rules:
    # Exclude go:generate from unused comment check
    - text: ".*//go:generate.*"
      linters:
        - unused
    # Exclude magic numbers in tests
    - path: _test\.go
      text: "magic number"
      linters:
        - gomnd
