name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: true

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  package:
    needs: goreleaser
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package_type: [deb, rpm]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: true

      - name: Install nfpm
        run: |
          go install github.com/goreleaser/nfpm/v2/cmd/nfpm@latest

      - name: Get version
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create ${{ matrix.package_type }} package
        run: |
          nfpm pkg --packager ${{ matrix.package_type }} \
            --target ./dist/dt_${{ steps.get_version.outputs.version }}_${{ matrix.package_type }}.${matrix.package_type}

      - name: Upload package to release
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/dt_${{ steps.get_version.outputs.version }}_${{ matrix.package_type }}.${{ matrix.package_type }}

  homebrew:
    needs: goreleaser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          formula: dt
          tag: ${{ github.ref }}
          revision: ${{ github.sha }}
